repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.4.2'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
        args: ["--with", "dev"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-all-unused-imports

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings
          - flake8-bugbear
          - flake8-builtins
          - flake8-print
          - flake8-pytest-style
          - flake8-return
          - flake8-simplify
          - flake8-annotations
        files: ^(pydiscovergy|script|tests)/.+\.py$

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: poetry run pylint pydiscovergy
        language: system
        always_run: true
        pass_filenames: false