language: python
python:
  - '3.7'
  - pypy

install:
  - pip install -r requirements.txt

script:
  - "python -m pytest tests/"

deploy:
  provider: pypi
  user: jpbe
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: jpbede/pydiscovergy
